rm the upstream from action

diff --git a/.github/workflows/follow-the-leader.yml b/.github/workflows/follow-the-leader.yml
--- a/.github/workflows/follow-the-leader.yml
+++ b/.github/workflows/follow-the-leader.yml
@@ -13,28 +13,25 @@ jobs:
         with:
           ref: develop/SchwurblAir
       - run: |
-          git rebase origin master || \
+          git rebase master || \
           (git rebase --abort && echo "Merge conflicts happened" && exit 100)
-          git push -f origin develop/SchwurblAir || \
-          (echo "Git force push failed" && exit 101)
+          git push -f || (echo "Git force push failed" && exit 101)
           echo "SchwurblAir Rebased"
 
       - uses: actions/checkout@v2
         with:
           ref: develop/SchwurblAir
       - run: |
-          git rebase origin master || \
+          git rebase master || \
           (git rebase --abort && echo "Merge conflicts happened" && exit 100)
-          git push -f origin develop/Schwurbler360 || \
-          (echo "Git force push failed" && exit 101)
+          git push -f || (echo "Git force push failed" && exit 101)
           echo "Schwurbl360 Rebased"
 
       - uses: actions/checkout@v2
         with:
           ref: develop/ToGo
       - run: |
-          git rebase origin master || \
+          git rebase master || \
           (git rebase --abort && echo "Merge conflicts happened" && exit 100)
-          git push -f origin develop/ToGo || \
-          (echo "Git force push failed" && exit 101)
+          git push -f || (echo "Git force push failed" && exit 101)
           echo "ToGo  Rebased"
