fix wrong branch

diff --git a/.github/workflows/follow-the-leader.yml b/.github/workflows/follow-the-leader.yml
--- a/.github/workflows/follow-the-leader.yml
+++ b/.github/workflows/follow-the-leader.yml
@@ -17,7 +17,7 @@ jobs:
         echo "SchwurblAir Rebased"
         git checkout -b develop/Schwurbler360 origin/develop/Schwurbler360
         git rebase master || (git rebase --abort && echo "Merge conflicts happened" && exit 100)
-        git push -f origin develop/SchwurblAir || (echo "Git force push failed" && exit 101)
+        git push -f origin develop/Schwurbler360 || (echo "Git force push failed" && exit 101)
         echo "Schwurbl360 Rebased"
         git checkout -b develop/ToGo origin/develop/ToGo
         git rebase master || (git rebase --abort && echo "Merge conflicts happened" && exit 100)
